---
title: STAT 457 Delinquency Problem 
author: Martha Eichlersmith
output:
  pdf_document:
    fig_caption: yes
header-includes:
  - \usepackage{color}
  - \usepackage{mathtools}
  - \usepackage{amsbsy} #bold in mathmode
  - \usepackage{nicefrac} # for nice fracs 
  - \usepackage{booktabs}
  - \usepackage{geometry}
  - \usepackage{caption} #to remove automatic table name and number - \captionsetup[table]{labelformat=empty}, put code under ---
geometry: "left=1.75cm,right=1.75cm,top=1.5cm,bottom=2cm" 

---
```{r setup, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
library(ggplot2) #ggplot
library(readr) #import CSV
library(gridExtra) #organize plots
library(grid) #organize plots
library(latex2exp) #latex in ggplot titles 
library(matlib) #A = matrix, inv(A) = A^{-1} 
library(numDeriv) #calculate numerical first and second order derivatives 
library(gtable) #for tablegrob functions 
#library(kableExtra) #for kable functions
library(dplyr) #for piping 
library(MCMCpack) #for dirichelt
knitr::opts_chunk$set(fig.width = 10, fig.height = 4)
knitr::opts_chunk$set(echo=FALSE)
decimal <- function(x, k) trimws(format(round(x, k), nsmall=k))
dec <- 5
#knitr::opts_chunk$set(echo=FALSE) #using knitr for this option but don't have to load 
```

Is delinquency related to birth order? 

```{r props}
alpha <- c(127, 123,  93, 17) #/360 #most delinquent
gamma <- c(345, 209, 158, 65) #/777 #least delinquent
parameters <- rbind(alpha, gamma)
total <- c(sum(alpha), sum(gamma))
diff <- c(alpha-gamma, sum(alpha-gamma))
table <- rbind( cbind(parameters, total), diff)
rownames(table) <- c("Most Delinquent", "Least Delinquent", "Difference (Most - Least)")
colnames(table) <- c("Oldest", "In-between", "Youngest", "Only Child", "Total")
knitr::kable(table, booktabs=TRUE, 'latex', digits=dec, caption="Row Proportion") %>%
  kableExtra::kable_styling(latex_options="hold_position" )

```

```{r function}
func_diff <- function(matrix){
diff.matrix <- cbind( #most - least
   matrix[,1] - matrix[,5] #diff for Oldest
  ,matrix[,2] - matrix[,6] #diff for in-between
  ,matrix[,3] - matrix[,7] #diff for youngest
  ,matrix[,4] - matrix[,8] #diff for only-child
   )
diff.matrix
}

func_values <- function(vec){
  it <- length(vec)
  CI.val <- decimal(quantile(vec, c(0.025, 0.975)), dec)
  CI.95 <- paste("(", paste(CI.val, collapse=", "), ")")
  mean <- decimal(mean(vec), dec)
  pval <- length(vec[vec > 0])/it 
  vec <- c(it, mean, CI.95, pval)
  vec
}

func_delinq <- function(it){
set.seed(050104)
prop <- rdirichlet(it, t(parameters))
diff <- cbind( #most - least
   prop[,1] - prop[,5] #diff for Oldest
  ,prop[,2] - prop[,6] #diff for in-between
  ,prop[,3] - prop[,7] #diff for youngest
  ,prop[,4] - prop[,8] #diff for only-child
   )
apply(diff, 2, func_values)
}

```

```{r calculation}
it.vec <- c(1e04, 1e05, 1e06)
it.1 <- func_delinq(it.vec[1])
it.2 <- func_delinq(it.vec[2])
it.3 <- func_delinq(it.vec[3])
```

```{r tables}
func_table <- function(i, name){
table <- cbind(it.1[,i], it.2[,i] , it.3[,i])
rownames(table) <- c("Iterations", "Mean", "95% CI", "P(diff>0)")
title <- paste("Difference in Proportion for", name, ": Most Delinquent - Least Delinquent")
#table
knitr::kable(table, booktabs=T, 'latex', caption=title) %>%
  kableExtra::kable_styling(latex_options="hold_position" ) #hold table in place 
}

func_table(1, "Oldest")
func_table(2, "In-Between")
func_table(3, "Youngest")
func_table(4, "Only")
```

```{r chisqtest}
func_pval.chisq <- function(pvals){
  x <- -2*sum(log(as.numeric(pvals)))
  combined.pval <-  pnorm(x, 2*length(pvals))
}

pvals.vec <- cbind(it.1[4,], pval.2 <- it.2[4,], pval.3 <- it.3[4,])

combined <- apply(pvals.vec, 2, func_pval.chisq)
combined.pvals <- rbind(it.vec, decimal(combined, dec))
rownames(combined.pvals) <- c("Iterations", "Combined p-value")

title <- paste("Combined p-values:","$X = -2\\sum_{i=1}^4(p_i) \\sim \\chi^2_{df=8}$")
combined.pvals 
#knitr::kable(combined.pvals, booktabs=T, 'latex', caption=title) %>%
#  kableExtra::kable_styling(latex_options="hold_position" )

```

There is evidence that birth order has an effect on delinquency rates.  There may be an argument that younger brothers are more delinquent, but my younger brother is not a delinquent (anecdotal evidence!).  


